/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SANJAY' at '7/8/19 11:48 AM' with Gradle 3.0
 *
 * @author SANJAY, @date 7/8/19 11:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
