/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SANJAY' at '7/9/19 2:41 PM' with Gradle 3.0
 *
 * @author SANJAY, @date 7/9/19 2:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
